name: Deploy to GitHub Pages

on: 
  push:
    branches:
      - main # Change this to your default branch if it's not main (e.g., master)

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          force_orphan: true
          commit_message: "Deploy to GitHub Pages"
          enable_jekyll: false
          keep_files: false
          # cname: example.com # Uncomment and replace with your custom domain if you have one 
